import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const getTextPromptScreenStyles = (currentTheme) => StyleSheet.create({  
  scrollViewLoggedIn: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 115,
    paddingTop: 215,
  },
  scrollViewLoggedOut: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 205,
    paddingBottom: 130,
  },
  container: {
    alignItems: 'center',
    marginTop: -100,
    maxWidth: width,
  },
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 26,
    fontWeight: '600',
    color:  currentTheme.textColor,
    marginBottom: 20,
    textAlign: 'center',
    marginTop: -40,
    paddingHorizontal: 20,
  },
  input: {
    width: width - 50,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#6200ea',
    borderWidth: 0,
    marginBottom: 20,
    fontSize: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    color: '#eee',
  },
  button: {
    backgroundColor: '#6200ea',
    paddingVertical: 13,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6200ea',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 16.5,
  },
  image: {
    width: 300,
    height: 300,
    borderRadius: 6,
    marginTop: 10,
    borderWidth: 1.5,
    borderColor: '#7049f6',
    shadowColor: '#0b0b16',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  favoritesTitle: {
    fontSize: 19,
    fontWeight: '500',
    color:  currentTheme.textColor,
    marginBottom: 11,
    textAlign: 'center',
  },
  favoritesButton: {
    backgroundColor: '#6200ea',
    paddingVertical: 11,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginTop: 17,
  },
  error: {
    color: '#9F0000',
    marginVertical: 10,
    fontSize: 16,
  },
  description: {
    fontSize: 15.5,
    color:  currentTheme.textColor,
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  previewContainer: {
    marginTop: 26,
    alignItems: 'center',
  },
  previewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  previewImage: {
    width: 104,
    height: 104,
    margin: 4,
  },
});