import { StyleSheet } from 'react-native';

export const getLoginScreenStyles = (currentTheme) => StyleSheet.create({  
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 25,
    backgroundColor: currentTheme.backgroundColor,
  },
  title: {
    fontSize: 26.5,
    fontWeight: '700',
    color: currentTheme.secondaryTextColor,
    marginBottom: 20,
    textAlign: 'center',
    marginTop: -50,
  },
  input: {
    width: '100%',
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#7049f6',
    borderWidth: 0,
    marginBottom: 20,
    fontSize: 16,
    color: '#eee',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  button: {
    backgroundColor: '#7049f6',
    paddingVertical: 13,
    paddingHorizontal: 11,
    borderRadius: 25,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '53%',
    shadowColor: '#6200ea',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 17,
  },
  error: {
    color: 'red',
    marginVertical: 10,
    fontSize: 16,
  },
  signupText: {
    marginTop: 20,
    color: currentTheme.tertiaryTextColor,
    fontSize: 16,
  },
  signupLink: {
    color: '#7049f6',
    fontWeight: '900',
  },
});